import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Navigate, NavLink, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { QueryClient, QueryClientProvider, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, ArrowUpRight, BarChart3, Bell, Building2, Check, ChevronLeft, ChevronRight, CircleDollarSign, CloudRain, FileText, LayoutDashboard, LogOut, Menu, Package, Plus, QrCode, Search, Settings, ShieldCheck, Ticket, Users, X } from 'lucide-react';
import { admin, api, messageOf, setAccessToken, type Analytics, type Station, type User } from './api';
import './styles.css';
import { Workspace } from './Workspace';

const AuthContext = createContext<{user:User|null; login:(email:string,password:string)=>Promise<void>; logout:()=>void}>({user:null,login:async()=>{},logout:()=>{}});
const useAuth=()=>useContext(AuthContext);
function AuthProvider({children}:{children:React.ReactNode}){ const [user,setUser]=useState<User|null>(null); const navigate=useNavigate(); useEffect(()=>{ if(localStorage.getItem('mizallah_access_token')) api.get('/auth/me').then(r=>setUser(r.data.user)).catch(()=>setAccessToken(null)); },[]); const login=async(email:string,password:string)=>{const {data}=await api.post('/auth/login',{email,password}); setAccessToken(data.accessToken); localStorage.setItem('mizallah_refresh_token',data.refreshToken); setUser(data.user); navigate('/app/dashboard');}; const logout=()=>{const token=localStorage.getItem('mizallah_refresh_token'); if(token) api.post('/auth/logout',{refreshToken:token}).catch(()=>{}); setAccessToken(null); localStorage.removeItem('mizallah_refresh_token'); setUser(null); navigate('/login');}; return <AuthContext.Provider value={{user,login,logout}}>{children}</AuthContext.Provider> }
function Protected(){const {user}=useAuth(); return user?.role==='ADMIN'?<Outlet/>:<Navigate to="/login" replace/>}
const nav=[['/app/dashboard','Overview',LayoutDashboard],['/app/umbrellas','Umbrellas',CloudRain],['/app/stations','Stations',Building2],['/app/rentals','Rentals',Ticket],['/app/users','Users',Users],['/app/pricing','Pricing plans',CircleDollarSign],['/app/payments','Payments',ArrowUpRight],['/app/damage-reports','Damage reports',ShieldCheck],['/app/rebalancing','Rebalancing',Package],['/app/audit-logs','Audit logs',FileText],['/app/analytics','Analytics',BarChart3]] as const;
function Layout(){const [open,setOpen]=useState(false); const {user,logout}=useAuth(); const location=useLocation(); const current=nav.find(n=>location.pathname.startsWith(n[0])); return <div className="shell"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><span className="brand-mark"><CloudRain size={18}/></span><span>Mizallah<small>ADMIN CONSOLE</small></span><button className="icon mobile-close" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>isActive?'nav-item active':'nav-item'}><Icon size={17}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-bottom"><div className="user-mini"><div className="avatar">{user?.name?.[0]}</div><div><b>{user?.name}</b><small>{user?.email}</small></div></div><button className="logout" onClick={logout}><LogOut size={16}/> Sign out</button></div></aside><main className="main"><header className="topbar"><button className="icon menu-btn" onClick={()=>setOpen(true)}><Menu size={21}/></button><div><div className="eyebrow">MIZALLAH / {current?.[1]?.toUpperCase()}</div><h1>{current?.[1] || 'Overview'}</h1></div><div className="top-actions"><button className="icon"><Bell size={19}/><i/></button><div className="top-avatar">{user?.name?.[0]}</div></div></header><div className="content"><Outlet/></div></main></div>}
function Login(){const {user,login}=useAuth(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); if(user)return <Navigate to="/app/dashboard"/>; return <div className="login-page"><div className="login-visual"><div className="brand login-brand"><span className="brand-mark"><CloudRain size={20}/></span><span>Mizallah<small>SMART UMBRELLA RENTAL</small></span></div><div className="visual-copy"><span className="kicker">LPU CAMPUS OPERATIONS</span><h1>Keep every<br/><em>journey dry.</em></h1><p>A calm command center for the people keeping Mizallah moving across campus.</p></div><div className="weather-note"><CloudRain size={18}/><span>OPERATIONS STATUS <b>ALL SYSTEMS NOMINAL</b></span></div></div><div className="login-form"><div className="form-inner"><span className="kicker">WELCOME BACK</span><h2>Sign in to Mizallah</h2><p className="muted">Use your administrator credentials to continue.</p>{error&&<div className="alert">{error}</div>}<label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="admin@lpu.test"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Enter your password"/></label><button className="primary full" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await login(email,password)}catch(e){setError(messageOf(e))}finally{setBusy(false)}}}>{busy?'Signing in...':'Continue'}<ArrowUpRight size={17}/></button><p className="legal">Authorized administrative access only.</p></div></div></div>}
function Stat({label,value,detail,icon:Icon,accent}:{label:string;value:string|number;detail:string;icon:typeof Activity;accent?:boolean}){return <div className={accent?'stat accent':'stat'}><div className="stat-top"><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><small>{detail}</small></div>}
function Dashboard(){const q=useQuery({queryKey:['analytics'],queryFn:admin.analytics}); const a=q.data; const count=(key:string)=>a?.umbrellasByStatus[key]??'Data unavailable'; return <><div className="welcome"><div><span className="kicker">MONDAY, AUGUST 24, 2026</span><h2>Good morning, operations.</h2><p>Here is the pulse of your umbrella network.</p></div><NavLink to="/app/umbrellas" className="primary"><Plus size={17}/> Add umbrella</NavLink></div>{q.isError&&<div className="alert">{messageOf(q.error)}</div>}<div className="stats"><Stat label="Available fleet" value={count('AVAILABLE')} detail="Ready to rent now" icon={CloudRain} accent/><Stat label="Currently rented" value={count('RENTED')} detail="Across campus" icon={Activity}/><Stat label="Active rentals" value={a?.currentlyActiveRentals??'Data unavailable'} detail="Includes overdue" icon={Ticket}/><Stat label="Verified revenue" value={a?`₹${(a.totalRevenuePaise/100).toLocaleString('en-IN')}`:'Data unavailable'} detail={`${a?.verifiedPaymentsCount??0} verified payments`} icon={CircleDollarSign}/></div><div className="grid-two"><section className="panel"><div className="panel-head"><div><span className="kicker">FLEET HEALTH</span><h3>Umbrella inventory</h3></div><NavLink to="/app/umbrellas" className="text-link">View all <ArrowUpRight size={14}/></NavLink></div><div className="inventory-list">{[['AVAILABLE','Ready for rental','status-green'],['RENTED','With students','status-gold'],['MAINTENANCE','Needs attention','status-gray'],['MISSING','Unaccounted for','status-gray']].map(([key,label,cls])=><div className="inventory-row" key={key}><span className={`dot ${cls}`}/><span>{label}</span><b>{count(key)}</b></div>)}</div></section><section className="panel insight"><div className="panel-head"><div><span className="kicker">LIVE SIGNAL</span><h3>Network snapshot</h3></div><span className="live"><i/> LIVE</span></div><div className="snapshot"><div className="pulse"><Activity size={25}/></div><div><b>Operations are running smoothly</b><p>Use the navigation to inspect stations, rentals and team activity.</p></div></div><div className="quote">“Small systems, thoughtfully run, make campus life better.”</div></section></div></>}

function AppRoutes(){return <Routes><Route path="/login" element={<Login/>}/><Route element={<Protected/>}><Route element={<Layout/>}><Route path="/app/dashboard" element={<Dashboard/>}/><Route path="/app/users" element={<Workspace resource="users"/>}/><Route path="/app/stations" element={<Workspace resource="stations"/>}/><Route path="/app/umbrellas" element={<Workspace resource="umbrellas"/>}/><Route path="/app/pricing" element={<Workspace resource="pricing"/>}/><Route path="/app/rentals" element={<Workspace resource="rentals"/>}/><Route path="/app/payments" element={<Workspace resource="payments"/>}/><Route path="/app/damage-reports" element={<Workspace resource="damage-reports"/>}/><Route path="/app/rebalancing" element={<Workspace resource="rebalancing-tasks"/>}/><Route path="/app/audit-logs" element={<Workspace resource="audit-logs"/>}/><Route path="/app/analytics" element={<Dashboard/>}/><Route path="/app/settings" element={<div className="empty"><Settings size={25}/><h3>Workspace preferences</h3><p>Frontend preferences are intentionally local. Server secrets and infrastructure settings are never exposed.</p></div>}/></Route></Route><Route path="*" element={<Navigate to="/app/dashboard" replace/>}/></Routes>}
function Root(){return <AuthProvider><AppRoutes/></AuthProvider>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient()}><BrowserRouter><Root/></BrowserRouter></QueryClientProvider>);
